---
- name: install depends first
  apt: name=python-apt state=present update_cache=yes

- name: install fish repo
  apt_repository:
    repo="deb https://download.opensuse.org/repositories/shells:/fish:/release:/{{ fish_major_version }}/Debian_{{ ansible_distribution_major_version }}.0/ /"
    filename="fish"
    state=present
    update_cache=yes
  when: ansible_distribution == "Debian"

- name: install fish repo
  apt_repository:
    repo="ppa:fish-shell/release-{{ fish_major_version }}"
    state=present
    update_cache=yes
  when: ansible_distribution == "Ubuntu"

- name: install fish
  apt: name=fish state=present
