---
- name: installing os centric piece first
  include_tasks: "os_family/{{ ansible_os_family }}.yml"

- name: make the fisher package manager directory
  file:
    path="{{ user.home }}/.config/fish/functions"
    state=directory
    owner="{{ user.name }}"
    mode=0755
    #recurse=yes

- block:
  - name: install fisher package manager
    get_url:
      url="{{ item.url }}"
      dest="{{ item.dest }}"
    with_items:
      - {url: "https://git.io/fisher", dest: "{{ user.home }}/.config/fish/functions/fisher.fish"}

    # the following task is not really idempotent
  - name: install fisher package manager addons
    command: /usr/bin/fish -c 'fisher add {{ item }}'
    register: fisherman_out
    changed_when: fisherman_out.stderr is regex(".*(added|removed)\ .*")
    failed_when: fisherman_out.stderr is regex(".*(cannot|invalid|unknown)\ .*")
    with_items:
      - "{{ fish_fisherman_packages }}"
    when: fish_fisherman_packages is defined

  - name: copy configuration file
    copy:
      content: '{{ fish_config }}'
      dest: ~/.config/fish/config.fish
      mode: '0644'
    when: fish_config is defined

  - name: append fish shell to .bashrc if chosen to do so
    lineinfile:
      path: ~/.bashrc
      line: exec fish
      insertafter: EOF
      create: yes
      state: present
    when:
    - fish_append_to_bash
    - fish_shell_activate

  # run this whole block as:
  become: yes
  become_user: "{{ user.name }}"
  become_method: su

- name: change the shell to fish if chosen to do so
  user:
    name="{{ user.name }}"
    shell=/usr/bin/fish
  when:
   - not fish_append_to_bash
   - fish_shell_activate
